// Chromara service worker.
// - One version, whole: the page and every script come from the same cache, named by a content hash, so a phone never
//   mixes files of two versions. The version is stamped by tools/build_pwa.cjs.
// - A new version downloads in the background and waits. The page decides when to switch (at the cover or the title,
//   or when the player asks), so an update never interrupts a game.
// - Music lives in its own cache keyed by each cue's revision: it survives game updates and is fetched once, in the
//   background, so the whole game plays without connection.
// <build_pwa> generated by tools/build_pwa.cjs, do not edit by hand
const VERSION = '02ccd81b81f2';
const SHELL = ["./", "./index.html", "./manifest.webmanifest", "./mobile.css", "./chromara-cuaderno.ttf", "./chromara-rotulo.ttf", "./icons/icon-192.png", "./icons/icon-512.png", "./icons/icon-maskable-192.png", "./icons/icon-maskable-512.png", "./icons/icon-180.png", "./data.js", "./music.js", "./music_cues.js", "./music_fallback.js", "./sfx_samples.js", "./sfx.js", "./audio.js", "./font.js", "./sprites.js", "./character_sprites.js", "./world_art.js", "./rinse.js", "./field.js", "./scene.js", "./gui.js", "./battle.js", "./attacks.js", "./combat.js", "./battle_ui.js", "./settings.js", "./mobile.js", "./chapter_art.js", "./chapters.js", "./prologue.js", "./game.js", "./pwa.js"];
const MUSIC = ["./music/title.opus.ogg?v=0c9b1f42d2fa", "./music/map.opus.ogg?v=528adc3d0be1", "./music/battle.opus.ogg?v=98e25341892e", "./music/boss.opus.ogg?v=f66c1614a5ed", "./music/victory.opus.ogg?v=15de814edf8e", "./music/gameover.opus.ogg?v=b65344bded99", "./music/atelier.opus.ogg?v=e2726779b0da", "./music/prelude.opus.ogg?v=344cbb43f2b8", "./music/restored.opus.ogg?v=6ec74bf3f22b"];
// </build_pwa>
const SHELL_CACHE = 'chromara-' + VERSION, MUSIC_CACHE = 'chromara-musica';

self.addEventListener('install', e => {
  // cache: 'reload' skips the HTTP cache, so a fresh version never installs stale copies from the CDN
  e.waitUntil(caches.open(SHELL_CACHE).then(c => c.addAll(SHELL.map(u => new Request(u, { cache: 'reload' })))));
});
self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k.startsWith('chromara') && k !== SHELL_CACHE && k !== MUSIC_CACHE) await caches.delete(k);
    // retired music revisions are dropped; current ones stay
    const music = await caches.open(MUSIC_CACHE), wanted = new Set(MUSIC.map(u => new URL(u, self.registration.scope).href));
    for (const req of await music.keys()) if (!wanted.has(req.url)) await music.delete(req);
    await self.clients.claim();
    for (const c of await self.clients.matchAll({ type: 'window' })) c.postMessage({ type: 'activated', version: VERSION });
  })());
});
async function cacheMusic(source) {
  const music = await caches.open(MUSIC_CACHE); let done = 0;
  for (const u of MUSIC) {
    try { if (!(await music.match(u))) { const r = await fetch(new Request(u, { cache: 'reload' })); if (r.ok) await music.put(u, r); } done++; } catch (_) {}
    source?.postMessage({ type: 'music', done, total: MUSIC.length });
  }
}
self.addEventListener('message', e => {
  const m = e.data || {};
  if (m.type === 'skip-waiting') self.skipWaiting();
  else if (m.type === 'version') e.source?.postMessage({ type: 'version', version: VERSION });
  else if (m.type === 'cache-music') e.waitUntil(cacheMusic(e.source));
});
self.addEventListener('fetch', e => {
  const req = e.request, url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== self.location.origin) return;
  // music: from its cache, or fetched once and kept
  if (url.pathname.includes('/music/') && url.pathname.endsWith('.opus.ogg')) {
    e.respondWith(caches.open(MUSIC_CACHE).then(async c => (await c.match(req)) || fetch(req).then(r => { if (r.ok && url.search) c.put(req, r.clone()); return r; })));
    return;
  }
  // the page and its files: always this version's copy; anything else (development tools) goes to the network
  if (req.mode === 'navigate' && !/\/(index\.html)?$/.test(url.pathname)) return; // other pages of the repository
  const page = req.mode === 'navigate';
  e.respondWith(caches.open(SHELL_CACHE).then(async c => (await c.match(page ? './index.html' : req, { ignoreSearch: true })) || fetch(req).catch(async () => page ? (await c.match('./index.html')) || Response.error() : Response.error())));
});
