/* Stamps one content version into the PWA. Every shipped file is hashed; the hash names the service worker's cache and
   the ?v= of every script in index.html, so a device always runs one coherent copy of the game and learns about a new
   one as soon as any file changes. Music cues keep their own revisions (music_cues.js) and survive game updates.

     node tools/build_pwa.cjs            rewrite sw.js and index.html with the current version
     node tools/build_pwa.cjs --check    exit 1 if they are stale (tools/test_pwa.cjs runs this)
     node tools/build_pwa.cjs --root DIR work on another copy of the site (used by the update test)                   */
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const args = process.argv.slice(2), check = args.includes('--check');
const root = args.includes('--root') ? path.resolve(args[args.indexOf('--root') + 1]) : path.join(__dirname, '..');
const read = f => fs.readFileSync(path.join(root, f));

// The shell: the page, its styles and fonts, icons and every script index.html loads when hosted.
const html = read('index.html').toString();
const list = html.match(/const scripts = \[([^\]]*)\]/)[1] + ',' + html.match(/scripts\.push\(('sfx_samples[^)]*)\)/)[1];
const scripts = [...list.matchAll(/'([^']+\.js)'/g)].map(m => m[1]);
const SHELL = ['index.html', 'manifest.webmanifest', 'mobile.css', 'chromara-cuaderno.ttf', 'chromara-rotulo.ttf',
  'icons/icon-192.png', 'icons/icon-512.png', 'icons/icon-maskable-192.png', 'icons/icon-maskable-512.png', 'icons/icon-180.png', ...scripts];
const cues = JSON.parse(read('music_cues.js').toString().match(/const MUSIC_CUES = (\{.*\});/)[1]);
const MUSIC = Object.entries(cues).filter(([name]) => fs.existsSync(path.join(root, 'music', name + '.opus.ogg'))).map(([name, c]) => `music/${name}.opus.ogg?v=${encodeURIComponent(c.revision)}`);

// index.html is hashed with its own version literal blanked, so stamping it does not change the hash.
const VERSION_RE = /(const version = location\.protocol === 'file:' \? Date\.now\(\) : ')([^']*)(')/, CSS_RE = /(href="mobile\.css\?v=)([^"]*)(")/;
const blank = h => h.replace(VERSION_RE, '$1$3').replace(CSS_RE, '$1$3');
const hash = crypto.createHash('sha256');
for (const f of SHELL) { hash.update(f + '\0'); hash.update(f === 'index.html' ? blank(html) : read(f)); }
hash.update(JSON.stringify(MUSIC));
const VERSION = hash.digest('hex').slice(0, 12);

const swFile = path.join(root, 'sw.js'), sw = fs.readFileSync(swFile, 'utf8');
const block = `// <build_pwa> generated by tools/build_pwa.cjs, do not edit by hand\nconst VERSION = '${VERSION}';\nconst SHELL = ${JSON.stringify(['./', ...SHELL.map(f => './' + f)], null, 0).replace(/","/g, '", "')};\nconst MUSIC = ${JSON.stringify(MUSIC.map(f => './' + f)).replace(/","/g, '", "')};\n// </build_pwa>`;
const nextSw = sw.replace(/\/\/ <build_pwa>[\s\S]*?\/\/ <\/build_pwa>/, block);
const nextHtml = html.replace(VERSION_RE, `$1${VERSION}$3`).replace(CSS_RE, `$1${VERSION}$3`);
if (require.main === module) {
for (const f of SHELL) if (!fs.existsSync(path.join(root, f))) { console.error('missing shell file: ' + f); process.exit(1); }
if (check) {
  const stale = [nextSw !== sw && 'sw.js', nextHtml !== html && 'index.html'].filter(Boolean);
  if (stale.length) { console.error(`PWA version is stale in ${stale.join(' and ')}: run node tools/build_pwa.cjs`); process.exit(1); }
  console.log('PWA version ' + VERSION + ' is current (' + SHELL.length + ' shell files, ' + MUSIC.length + ' music cues).');
} else {
  fs.writeFileSync(swFile, nextSw); fs.writeFileSync(path.join(root, 'index.html'), nextHtml);
  console.log('PWA version ' + VERSION + ' (' + SHELL.length + ' shell files, ' + MUSIC.length + ' music cues).');
}
}
module.exports = { VERSION, SHELL, MUSIC };
