/* Pack the ImageGen cutouts into game-sized, bottom-anchored RGBA atlases.
   NODE_PATH=<directory containing sharp> node tools/pack_character_atlas.cjs
   Artwork/background extraction is done with ImageGen; this compiler only
   slices its alpha cutouts, normalizes their scale and packs game textures. */
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const sharp = require('sharp');
const root = path.resolve(__dirname, '..');
const input = path.join(root, 'artifacts/sprite-study-2026-09-21/cutouts');
const output = path.join(root, 'assets/characters');
const ids = ['carmin', 'ambar', 'anil'];
const sizes = { overworld: { cell: [32, 28], height: [18, 21, 20] }, battle: { cell: [48, 40], height: [25, 30, 28] } };
const median = values => values.slice().sort((a,b) => a-b)[Math.floor(values.length / 2)];

async function pack(id, mode) {
  const source = path.join(input, `${id}-${mode}.png`);
  const { data, info } = await sharp(source).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  if (info.width % 4 || info.height % 4) throw Error(`${source}: expected a 4×4 grid`);
  // Generated study sheets are visually gridded, not exact atlas grids. Locate
  // their empty gutters before slicing; fixed quarters can clip a hat or crest.
  function cuts(axis,start=0,end=null) {
    const length=axis==='x'?info.width:info.height,other=axis==='x'?info.height:info.width;
    const occupied=Array(length).fill(0);
    for(let a=0;a<length;a++)for(let b=start;b<(end??other);b++){
      const x=axis==='x'?a:b,y=axis==='x'?b:a;
      if(data[(y*info.width+x)*4+3]>=128)occupied[a]++;
    }
    const result=[0];
    for(let n=1;n<4;n++){
      const target=length*n/4,lo=Math.floor(target-length/16),hi=Math.ceil(target+length/16),gaps=[];
      for(let a=lo;a<=hi;a++)if(!occupied[a]){
        const start=a;while(a<hi&&!occupied[a+1])a++;
        gaps.push({mid:Math.round((start+a)/2),width:a-start+1});
      }
      gaps.sort((a,b)=>Math.abs(a.mid-target)-Math.abs(b.mid-target));
      if(!gaps.length)throw Error(`${id}/${mode}: no clear ${axis} gutter ${n}`);
      result.push(gaps[0].mid);
    }
    return [...result,length];
  }
  const xs=cuts('x'),columns=xs.slice(0,4).map((x,i)=>cuts('y',x,xs[i+1]));
  const frames = [];
  for (let index = 0; index < 16; index++) {
    const col=index%4,row=index>>2,ys=columns[col],sw=xs[col+1]-xs[col],sh=ys[row+1]-ys[row];
    const pixels = Buffer.alloc(sw * sh * 4);
    let x0=sw, y0=sh, x1=-1, y1=-1, opaque=0, clear=0;
    for (let y=0;y<sh;y++) for(let x=0;x<sw;x++) {
      const from = ((ys[row]+y)*info.width+xs[col]+x)*4, to=(y*sw+x)*4;
      // Binary alpha preserves the pixel-art contour without a matte fringe.
      if (data[from+3] < 128) { clear++; continue; }
      data.copy(pixels,to,from,from+3); pixels[to+3]=255; opaque++;
      x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);
    }
    if (opaque < 100 || clear < sw*sh*.25) throw Error(`${id}/${mode}/${index}: missing sprite or invalid alpha`);
    if (x0===0 || y0===0 || x1===sw-1 || y1===sh-1) throw Error(`${id}/${mode}/${index}: touches cell boundary`);
    frames.push({pixels,sw,sh,origin:[xs[col],ys[row]],box:{left:x0,top:y0,width:x1-x0+1,height:y1-y0+1},index});
  }
  const config=sizes[mode], [cw,ch]=config.cell;
  // One scale per sheet, measured from normal poses, never enlarge a flattened KO.
  let scale=config.height[ids.indexOf(id)]/median(frames.slice(0,4).map(f=>f.box.height));
  scale=Math.min(scale,...frames.map(f=>Math.min((cw-4)/f.box.width,(ch-3)/f.box.height)));
  const atlas=Buffer.alloc(cw*4*ch*4*4), meta=[];
  for(const f of frames) {
    const w=Math.max(1,Math.round(f.box.width*scale)),h=Math.max(1,Math.round(f.box.height*scale));
    const resized=await sharp(f.pixels,{raw:{width:f.sw,height:f.sh,channels:4}}).extract(f.box).resize(w,h,{kernel:'nearest'}).raw().toBuffer();
    const left=Math.floor((cw-w)/2),top=ch-h;
    for(let y=0;y<h;y++) resized.copy(atlas,(((f.index>>2)*ch+top+y)*cw*4+(f.index%4)*cw+left)*4,y*w*4,(y+1)*w*4);
    meta.push({index:f.index,sourceOrigin:f.origin,sourceBox:f.box,box:{x:left,y:top,w,h},anchor:[cw/2,ch]});
  }
  const png=await sharp(atlas,{raw:{width:cw*4,height:ch*4,channels:4}}).png({palette:true,colours:48,dither:0}).toBuffer();
  fs.writeFileSync(path.join(output,`${id}-${mode}.png`),png);
  console.log(`${id}/${mode}: 16 frames, ${cw}×${ch} cells, ${png.length} bytes`);
  return {cell:config.cell,scale,frames:meta,image:'data:image/png;base64,'+png.toString('base64')};
}
(async()=>{
  fs.mkdirSync(output,{recursive:true});
  const sheets={};
  for(const id of ids){sheets[id]={};for(const mode of Object.keys(sizes))sheets[id][mode]=await pack(id,mode);}
  const data={version:1,sheets};
  fs.writeFileSync(path.join(output,'atlas.js'),'// Generated by tools/pack_character_atlas.cjs; embedded PNGs also work over file://.\nwindow.CHARACTER_ATLAS = '+JSON.stringify(data)+';\n');
  fs.writeFileSync(path.join(output,'manifest.json'),JSON.stringify({version:1,sheets:Object.fromEntries(ids.map(id=>[id,Object.fromEntries(Object.entries(sheets[id]).map(([mode,{image,...rest}])=>[mode,{...rest,file:`${id}-${mode}.png`}]))]))},null,2)+'\n');
})().catch(error=>{console.error(error);process.exitCode=1;});
